services:
  db:
    image: postgres:16
    container_name: enrollsys_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: enrollsys
      POSTGRES_USER: enrollsys
      POSTGRES_PASSWORD: enrollsys_password
    volumes:
      - enrollsys_pgdata:/var/lib/postgresql/data

volumes:
  enrollsys_pgdata:
